eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaulZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
